http:
  routers:
    traefik:
      rule: "Host(`traefikboard.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "*.localhost"

tls:
  certificates:
    - certFile: "/etc/certs/fake.crt"
      keyFile: "/etc/certs/fake.key"
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/fake.crt
        keyFile: /etc/certs/fake.key
