global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true # Traefik watch docker event
    exposedByDefault: false # Disallow creation route for container
    network: hostmanager

  file:
    filename: /etc/traefik/dynamic_conf.yaml
    watch: true

accessLog:
  addInternals: true

log:
  level: ERROR
  format: common

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ':443'
