global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    useBindPortIP: true # tell Traefik to use the IP/Port attached to the container's binding instead of its inner network IP/Port
    exposedByDefault: false
    network: hostmanager

  file:
    filename: /etc/traefik/dynamic_conf.yaml

accessLog: {}

log:
  level: ERROR
  format: common

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ':443'

  database:
    address: ':3316/tcp'
