# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node

  publish-docker-hub:
    needs: [release-please]
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        env:
          OUTPUT: ${{ needs.release-please.outputs.release_created }}
        run: echo "$OUTPUT"
#    if: ${{ job.release-please.outputs.release_created }}
#    uses: mihani/traefik-docker-hostmanager/.github/workflows/publish-docker-hub.yml@main
